version: '3.3'
services:
  traefik:
    image: traefik:latest
    command: --web --docker --docker.domain=keras --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "48080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - "traefik.dashboard.rule=Host:keras;PathPrefix:/app"
      - "traefik.dashboard.port=9000"
      - "traefik.parse-server.rule=Host:keras;PathPrefix:/parse"
      - "traefik.parse-server.port=1337"
  parse-server:
    extends:
      file: backend/docker-compose.yml
      service: parse-server
      
  dashboard:
    build:
      context: .
      dockerfile: ./Docker/frontend.dockerfile
    # ports:
    #   - "44444:8080"
    volumes:
      - ./frontend:/app

